### ISSUE TITLE
Containerise webapp

### ISSUE THREAD

**Issue by alexmassen-hane** [ADACS-Australia/GleamXGPMonitoring#17]
**Issue** 
The current version of the webapp can be difficult to manage as it is run directly using a mix of an nginx service and uwsgi on the host machine. 

**Solution**
Containerising the django, nginx and postgres database portions into their own docker containers running in the same docker network will make it easier to troubleshoot and redeploy the webapp if needed.

**Comment by PaulHancock** [comment]
Duplicated by #26, so closing this issue.
