### ISSUE TITLE
Searching by position on ratings table generates "cursor already closed"

### ISSUE THREAD

**Issue by nhurleywalker** [ADACS-Australia/GleamXGPMonitoring#19]
When I search for candidates in the candidate table view, I get errors (shown below). I triggered this by searching on position using the format requested on the page, with a search radius of 60 arcmin.

![Screenshot from 2024-02-07 14-07-02](https://github.com/ADACS-Australia/GleamXGPMonitoring/assets/8326966/64f02d34-7926-4ee2-baba-57e94ad93907)

`<div id="summary" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(255, 255, 204); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="padding: 0px; margin: 0px; font-weight: normal;">InterfaceError at /candidate_table/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87);">cursor already closed</pre>
Request Method: | POST
-- | --
https://mwa-image-plane.duckdns.org/candidate_table/
4.0.3
InterfaceError
cursor already closed
/home/ubuntu/.local/lib/python3.8/site-packages/django/db/utils.py, line 98, in inner
/home/ubuntu/.local/bin/uwsgi
3.8.10
['.',  '',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/home/ubuntu/.local/lib/python3.8/site-packages',  '/usr/local/lib/python3.8/dist-packages',  '/shpc',  '/usr/lib/python3/dist-packages']
Wed, 07 Feb 2024 06:06:56 +0000

</div><div id="explanation" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(238, 238, 238); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="padding: 0px; margin: 0px;">You’re seeing this error because you have<span> </span><code style="padding: 0px; margin: 0px; font-size: 10.5625px; white-space: pre-wrap;">DEBUG = True</code><span> </span>in your Django settings file. Change that to<span> </span><code style="padding: 0px; margin: 0px; font-size: 10.5625px; white-space: pre-wrap;">False</code>, and Django will display a standard page generated by the handler for this status code.</p></div>InterfaceError at /candidate_table/
cursor already closed
Request Method:	POST
Request URL:	https://mwa-image-plane.duckdns.org/candidate_table/
Django Version:	4.0.3
Exception Type:	InterfaceError
Exception Value:	
cursor already closed
Exception Location:	/home/ubuntu/.local/lib/python3.8/site-packages/django/db/utils.py, line 98, in inner
Python Executable:	/home/ubuntu/.local/bin/uwsgi
Python Version:	3.8.10
Python Path:	
['.',
 '',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '/home/ubuntu/.local/lib/python3.8/site-packages',
 '/usr/local/lib/python3.8/dist-packages',
 '/shpc',
 '/usr/lib/python3/dist-packages']
Server time:	Wed, 07 Feb 2024 06:06:56 +0000
Error during template rendering
In template /home/ubuntu/GleamXGPMonitoring/gleam_webapp/templates/candidate_app/candidate_table.html, error at line 23

cursor already closed
13	    <div class="row justify-content-center" style="background-color:#f8f8f8; margin: 0;">
14	      <div class="col-3">
15	        <div class="fieldWrapper">
16	          {{ form.rating_cutoff.errors }}
17	          <label for="{{ form.rating_cutoff.id_for_label }}">Average rating cutoff:</label>
18	          {{ form.rating_cutoff }}
19	        </div>
20	        <div class="fieldWrapper">
21	          {{ form.observation_id.errors }}
22	          <label for="{{ form.observation_id.id_for_label }}">Observation ID:</label>
23	          {{ form.observation_id }}
24	        </div>
25	        <div class="fieldWrapper">
26	          {{ form.column_display.errors }}
27	          <label for="{{ form.column_display.id_for_label }}">Display Count Columns:</label>
28	          {{ form.column_display }}
29	        </div>
30	        <div class="fieldWrapper">
31	          {{ form.order_by.errors }}
32	          <label for="{{ form.order_by.id_for_label }}">Order by:</label>
33	          {{ form.order_by }}
Traceback [Switch back to interactive view](https://mwa-image-plane.duckdns.org/candidate_table/#)
Environment:

Request Method: POST
Request URL: https://mwa-image-plane.duckdns.org/candidate_table/

Django Version: 4.0.3
Python Version: 3.8.10
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'rest_framework.authtoken',
 'candidate_app']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Template error:
In template /home/ubuntu/GleamXGPMonitoring/gleam_webapp/templates/candidate_app/candidate_table.html, error at line 23
   cursor already closed
   13 :     <div class="row justify-content-center" style="background-color:#f8f8f8; margin: 0;">
   14 :       <div class="col-3">
   15 :         <div class="fieldWrapper">
   16 :           {{ form.rating_cutoff.errors }}
   17 :           <label for="{{ form.rating_cutoff.id_for_label }}">Average rating cutoff:</label>
   18 :           {{ form.rating_cutoff }}
   19 :         </div>
   20 :         <div class="fieldWrapper">
   21 :           {{ form.observation_id.errors }}
   22 :           <label for="{{ form.observation_id.id_for_label }}">Observation ID:</label>
   23 :            {{ form.observation_id }} 
   24 :         </div>
   25 :         <div class="fieldWrapper">
   26 :           {{ form.column_display.errors }}
   27 :           <label for="{{ form.column_display.id_for_label }}">Display Count Columns:</label>
   28 :           {{ form.column_display }}
   29 :         </div>
   30 :         <div class="fieldWrapper">
   31 :           {{ form.order_by.errors }}
   32 :           <label for="{{ form.order_by.id_for_label }}">Order by:</label>
   33 :           {{ form.order_by }}

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)

The above exception (cursor already closed) was the direct cause of the following exception:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/GleamXGPMonitoring/gleam_webapp/./candidate_app/views.py", line 464, in candidate_table
    return render(request, 'candidate_app/candidate_table.html', content)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/base.py", line 1065, in render
    return render_value_in_context(output, context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/template/base.py", line 1042, in render_value_in_context
    value = str(value)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/utils/html.py", line 382, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/forms/boundfield.py", line 99, in as_widget
    return widget.render(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/forms/widgets.py", line 275, in render
    context = self.get_context(name, value, attrs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/forms/widgets.py", line 729, in get_context
    context = super().get_context(name, value, attrs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/forms/widgets.py", line 688, in get_context
    context["widget"]["optgroups"] = self.optgroups(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/forms/widgets.py", line 628, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/forms/models.py", line 1400, in __iter__
    for obj in queryset:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/query.py", line 401, in _iterator
    yield from self._iterable_class(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/query.py", line 87, in __iter__
    for row in compiler.results_iter(results):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1873, in cursor_iter
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1873, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)

Exception Type: InterfaceError at /candidate_table/
Exception Value: cursor already closed

Request information
USER
nhurleywalker

GET
No GET data

POST
Variable	Value
csrfmiddlewaretoken	
'0N4pbdZ3xh37giFC33uiOiU06cUwr1XGXe0RGYOdbEYfs8QINkSEjYgcHw2E0ctj'
rating_cutoff	
''
observation_id	
''
column_display	
'None'
order_by	
'avg_rating'
asc_dec	
'-'
ra_hms	
'18:32:00'
dec_dms	
'-09:11:00'
search_radius_arcmin	
'60'
FILES
No FILES data

COOKIES
Variable	Value
csrftoken	
'XCYlI0GA328VCb8ocTaeaiWpH3NDf7K8U3UNdLvKHp33O1juWayAFYiBinVLOigL'
sessionid	
'2j5dsoroyfjoicdfoxhjk8ntdbjy74d4'
META
Variable	Value
CONTENT_LENGTH	
'231'
CONTENT_TYPE	
'application/x-www-form-urlencoded'
CSRF_COOKIE	
'XCYlI0GA328VCb8ocTaeaiWpH3NDf7K8U3UNdLvKHp33O1juWayAFYiBinVLOigL'
CSRF_COOKIE_NEEDS_UPDATE	
True
DOCUMENT_ROOT	
'/usr/share/nginx/html'
HTTPS	
'on'
HTTP_ACCEPT	
'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7'
HTTP_ACCEPT_ENCODING	
'gzip, deflate, br'
HTTP_ACCEPT_LANGUAGE	
'en-US,en;q=0.9'
HTTP_CACHE_CONTROL	
'max-age=0'
HTTP_CONNECTION	
'keep-alive'
HTTP_CONTENT_LENGTH	
'231'
HTTP_CONTENT_TYPE	
'application/x-www-form-urlencoded'
HTTP_COOKIE	
('csrftoken=XCYlI0GA328VCb8ocTaeaiWpH3NDf7K8U3UNdLvKHp33O1juWayAFYiBinVLOigL; '
 'sessionid=2j5dsoroyfjoicdfoxhjk8ntdbjy74d4')
HTTP_HOST	
'mwa-image-plane.duckdns.org'
HTTP_ORIGIN	
'https://mwa-image-plane.duckdns.org'
HTTP_REFERER	
'https://mwa-image-plane.duckdns.org/candidate_table/'
HTTP_SEC_CH_UA	
'"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"'
HTTP_SEC_CH_UA_MOBILE	
'?0'
HTTP_SEC_CH_UA_PLATFORM	
'"Linux"'
HTTP_SEC_FETCH_DEST	
'document'
HTTP_SEC_FETCH_MODE	
'navigate'
HTTP_SEC_FETCH_SITE	
'same-origin'
HTTP_SEC_FETCH_USER	
'?1'
HTTP_UPGRADE_INSECURE_REQUESTS	
'1'
HTTP_USER_AGENT	
('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) '
 'Chrome/120.0.0.0 Safari/537.36')
PATH_INFO	
'/candidate_table/'
QUERY_STRING	
''
REMOTE_ADDR	
'134.7.50.183'
REMOTE_PORT	
'45050'
REQUEST_METHOD	
'POST'
REQUEST_SCHEME	
'https'
REQUEST_URI	
'/candidate_table/'
SCRIPT_NAME	
''
SERVER_NAME	
'mwa-image-plane.duckdns.org'
SERVER_PORT	
'443'
SERVER_PROTOCOL	
'HTTP/1.1'
uwsgi.node	
b'mwa-image-plane-v2'
uwsgi.version	
b'2.0.20'
wsgi.errors	
<_io.TextIOWrapper name=2 mode='w' encoding='UTF-8'>
wsgi.file_wrapper	
<built-in function uwsgi_sendfile>
wsgi.input	
<uwsgi._Input object at 0x7f8430b046b0>
wsgi.multiprocess	
True
wsgi.multithread	
False
wsgi.run_once	
False
wsgi.url_scheme	
'https'
wsgi.version	
(1, 0)
Settings
Using settings module gleam_webapp.settings
Setting	Value
ABSOLUTE_URL_OVERRIDES	
{}
ADMINS	
[]
ALLOWED_HOSTS	
['127.0.0.1', 'localhost', 'mwa-image-plane.duckdns.org']
APPEND_SLASH	
True
AUTHENTICATION_BACKENDS	
['django.contrib.auth.backends.ModelBackend']
AUTH_PASSWORD_VALIDATORS	
'********************'
AUTH_USER_MODEL	
'auth.User'
BASE_DIR	
PosixPath('/home/ubuntu/GleamXGPMonitoring/gleam_webapp')
CACHES	
{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
CACHE_MIDDLEWARE_ALIAS	
'default'
CACHE_MIDDLEWARE_KEY_PREFIX	
'********************'
CACHE_MIDDLEWARE_SECONDS	
600
CSRF_COOKIE_AGE	
31449600
CSRF_COOKIE_DOMAIN	
None
CSRF_COOKIE_HTTPONLY	
False
CSRF_COOKIE_NAME	
'csrftoken'
CSRF_COOKIE_PATH	
'/'
CSRF_COOKIE_SAMESITE	
'Lax'
CSRF_COOKIE_SECURE	
False
CSRF_FAILURE_VIEW	
'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME	
'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS	
[]
CSRF_USE_SESSIONS	
False
DATABASES	
{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.postgresql_psycopg2',
             'HOST': 'localhost',
             'NAME': 'mwa_image_plane_db',
             'OPTIONS': {},
             'PASSWORD': '********************',
             'PORT': '',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIGRATE': True,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': None,
             'USER': 'mwa_image_plane_admin'}}
DATABASE_ROUTERS	
[]
DATA_UPLOAD_MAX_MEMORY_SIZE	
2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS	
1000
DATETIME_FORMAT	
'N j, Y, P'
DATETIME_INPUT_FORMATS	
['%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M']
DATE_FORMAT	
'N j, Y'
DATE_INPUT_FORMATS	
['%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y']
DEBUG	
True
DEBUG_PROPAGATE_EXCEPTIONS	
False
DECIMAL_SEPARATOR	
'.'
DEFAULT_AUTO_FIELD	
'django.db.models.BigAutoField'
DEFAULT_CHARSET	
'utf-8'
DEFAULT_EXCEPTION_REPORTER	
'django.views.debug.ExceptionReporter'
DEFAULT_EXCEPTION_REPORTER_FILTER	
'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE	
'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL	
'webmaster@localhost'
DEFAULT_INDEX_TABLESPACE	
''
DEFAULT_TABLESPACE	
''
DISALLOWED_USER_AGENTS	
[]
EMAIL_BACKEND	
'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST	
'localhost'
EMAIL_HOST_PASSWORD	
'********************'
EMAIL_HOST_USER	
''
EMAIL_PORT	
25
EMAIL_SSL_CERTFILE	
None
EMAIL_SSL_KEYFILE	
'********************'
EMAIL_SUBJECT_PREFIX	
'[Django] '
EMAIL_TIMEOUT	
None
EMAIL_USE_LOCALTIME	
False
EMAIL_USE_SSL	
False
EMAIL_USE_TLS	
False
FILE_UPLOAD_DIRECTORY_PERMISSIONS	
None
FILE_UPLOAD_HANDLERS	
['django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE	
2621440
FILE_UPLOAD_PERMISSIONS	
420
FILE_UPLOAD_TEMP_DIR	
None
FIRST_DAY_OF_WEEK	
0
FIXTURE_DIRS	
[]
FORCE_SCRIPT_NAME	
None
FORMAT_MODULE_PATH	
None
FORM_RENDERER	
'django.forms.renderers.DjangoTemplates'
IGNORABLE_404_URLS	
[]
INSTALLED_APPS	
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'rest_framework.authtoken',
 'candidate_app']
INTERNAL_IPS	
[]
LANGUAGES	
[('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ar-dz', 'Algerian Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('dsb', 'Lower Sorbian'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-co', 'Colombian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gd', 'Scottish Gaelic'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hsb', 'Upper Sorbian'),
 ('hu', 'Hungarian'),
 ('hy', 'Armenian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('ig', 'Igbo'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kab', 'Kabyle'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('ky', 'Kyrgyz'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('ms', 'Malay'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmål'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('tg', 'Tajik'),
 ('th', 'Thai'),
 ('tk', 'Turkmen'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('uz', 'Uzbek'),
 ('vi', 'Vietnamese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese')]
LANGUAGES_BIDI	
['he', 'ar', 'ar-dz', 'fa', 'ur']
LANGUAGE_CODE	
'en-us'
LANGUAGE_COOKIE_AGE	
None
LANGUAGE_COOKIE_DOMAIN	
None
LANGUAGE_COOKIE_HTTPONLY	
False
LANGUAGE_COOKIE_NAME	
'django_language'
LANGUAGE_COOKIE_PATH	
'/'
LANGUAGE_COOKIE_SAMESITE	
None
LANGUAGE_COOKIE_SECURE	
False
LOCALE_PATHS	
[]
LOGGING	
{}
LOGGING_CONFIG	
'logging.config.dictConfig'
LOGIN_REDIRECT_URL	
'/'
LOGIN_URL	
'/accounts/login/'
LOGOUT_REDIRECT_URL	
'/'
MANAGERS	
[]
MEDIA_ROOT	
'/home/ubuntu/GleamXGPMonitoring/gleam_webapp/media'
MEDIA_URL	
'/media/'
MESSAGE_STORAGE	
'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE	
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']
MIGRATION_MODULES	
{}
MONTH_DAY_FORMAT	
'F j'
NUMBER_GROUPING	
0
PASSWORD_HASHERS	
'********************'
PASSWORD_RESET_TIMEOUT	
'********************'
PREPEND_WWW	
False
ROOT_URLCONF	
'gleam_webapp.urls'
SECRET_KEY	
'********************'
SECURE_CONTENT_TYPE_NOSNIFF	
True
SECURE_CROSS_ORIGIN_OPENER_POLICY	
'same-origin'
SECURE_HSTS_INCLUDE_SUBDOMAINS	
False
SECURE_HSTS_PRELOAD	
False
SECURE_HSTS_SECONDS	
0
SECURE_PROXY_SSL_HEADER	
None
SECURE_REDIRECT_EXEMPT	
[]
SECURE_REFERRER_POLICY	
'same-origin'
SECURE_SSL_HOST	
None
SECURE_SSL_REDIRECT	
False
SERVER_EMAIL	
'root@localhost'
SESSION_CACHE_ALIAS	
'default'
SESSION_COOKIE_AGE	
1209600
SESSION_COOKIE_DOMAIN	
None
SESSION_COOKIE_HTTPONLY	
True
SESSION_COOKIE_NAME	
'sessionid'
SESSION_COOKIE_PATH	
'/'
SESSION_COOKIE_SAMESITE	
'Lax'
SESSION_COOKIE_SECURE	
False
SESSION_ENGINE	
'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE	
False
SESSION_FILE_PATH	
None
SESSION_SAVE_EVERY_REQUEST	
False
SESSION_SERIALIZER	
'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE	
'gleam_webapp.settings'
SHORT_DATETIME_FORMAT	
'm/d/Y P'
SHORT_DATE_FORMAT	
'm/d/Y'
SIGNING_BACKEND	
'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS	
[]
STATICFILES_DIRS	
('/home/ubuntu/GleamXGPMonitoring/gleam_webapp/static/',)
STATICFILES_FINDERS	
['django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATICFILES_STORAGE	
'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_ROOT	
'/home/ubuntu/GleamXGPMonitoring/gleam_webapp/static_host/'
STATIC_URL	
'/static/'
TEMPLATES	
[{'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': ['/home/ubuntu/GleamXGPMonitoring/gleam_webapp/templates'],
  'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
                                     'django.template.context_processors.request',
                                     'django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages']}}]
TEMPLATES_DIR	
'/home/ubuntu/GleamXGPMonitoring/gleam_webapp/templates'
TEST_NON_SERIALIZED_APPS	
[]
TEST_RUNNER	
'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR	
','
TIME_FORMAT	
'P'
TIME_INPUT_FORMATS	
['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
TIME_ZONE	
'UTC'
USE_DEPRECATED_PYTZ	
False
USE_I18N	
True
USE_L10N	
True
USE_THOUSAND_SEPARATOR	
False
USE_TZ	
True
USE_X_FORWARDED_HOST	
False
USE_X_FORWARDED_PORT	
False
WSGI_APPLICATION	
'gleam_webapp.wsgi.application'
X_FRAME_OPTIONS	
'DENY'
YEAR_MONTH_FORMAT	
'F Y'
You’re seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.`

**Comment by PaulHancock** [comment]
"wontfix" is as close to "cannot reproduce as I can find.

**Comment by PaulHancock** [comment]
I have replaced this page with a new version so this bug is now closed.
