### ISSUE TITLE
Mismatch between candidate classifications in table vs. individual candidate view

### ISSUE THREAD

**Issue by nhurleywalker** [ADACS-Australia/GleamXGPMonitoring#21]
The candidates table search view, heading view, and the options available to classify a candidate, are all inconsistent with each other, which is confusing.

![ratee_this_candidate](https://github.com/ADACS-Australia/GleamXGPMonitoring/assets/8326966/7f9d10e1-3b9f-4ff2-82ce-97b6e3a27058)
![ratings_table_headings](https://github.com/ADACS-Australia/GleamXGPMonitoring/assets/8326966/ef3f045b-2bda-4193-9f85-8589e4c07f6d)
![ratings_table](https://github.com/ADACS-Australia/GleamXGPMonitoring/assets/8326966/c62f14a0-e939-444e-80bd-d16a347fda48)

**Comment by PaulHancock** [comment]
@nhurleywalker @robotopia : We discussed the usefulness of this page. In particular, do we need all the columns currently listed?

Maybe a replacement issue would be to redesign the types of candidates that can be selected.
That would mean having some pre-made types as a default and then let people change these types on a per-project basis via the admin interface (or similar). Pages such as this one would then be redesigned to be dynamic and have options/columns that correspond to these classification types.

What do you think?

**Comment by PaulHancock** [comment]
Oh my suggestion is what we already agreed to do in #24. I'll close this issue.
