### ISSUE TITLE
Would like to split candidates by project

### ISSUE THREAD

**Issue by nhurleywalker** [ADACS-Australia/GleamXGPMonitoring#22]
We need to be able to separate the candidate table into specific “projects” so that a user (or set of users) can examine the results from one project at a time, rather than them all being grouped together.

**Comment by PaulHancock** [comment]
In branch `22-split-candidates-by-project` I have added a new model for Project, and now each candidate is linked to a given project. When viewing candidates on the `candidate_table` or `candidate_rating` pages, only the candidates from the current project will be shown.

Users can change the project they are working on via the `session_settings` page.

Projects can be created/edited/removed via the `/admin/` interface. Removing a project will delete all the candidates associated with it.

@nhurleywalker / @robotopia: Do **Observations** also belong to a project?

**Comment by robotopia** [comment]
I would say "yes", as long as it's ManyToMany. @nhurleywalker does that sound ok?
