### ISSUE TITLE
Export to SAMP or FITS

### ISSUE THREAD

**Issue by nhurleywalker** [ADACS-Australia/GleamXGPMonitoring#23]
We need an improved export function so that we may more conveniently and quickly examine large numbers
of candidates. Ideally, this would allow us to broadcast a selection to SAMP (to be picked up by TopCat) or exported as a FITS table. This will be more time-efficient than designing in-browser viewing options.

**Comment by PaulHancock** [comment]
Exporting data directly via SAMP is problematic due to HTTP/HTTPS issues (see [2020ASPC..527...85T](https://ui.adsabs.harvard.edu/link_gateway/2020ASPC..527...85T/doi:10.48550/arXiv.1912.00917)).
As noted in the linked article: 

> Users of those services will just have to save files to local disk and reload them into a suitable local application rather than use a “send to TOPCAT” button or similar. This is a loss of convenience, but since more complex uses of Web SAMP such as exchanging coordinates between web and desktop clients are uncommon, it won’t have much impact on what users are actually able to do.

**Comment by PaulHancock** [comment]
In branch `23-vo-approach` I tried to implement a vo service using (CASDA_VO_tools)[https://github.com/csiro-rds/casda_vo_tools]) as the documentation indicated that it would provide a ready-made but customisable  way of providing VO compliant SIA/TAP services based on an existing database.

After much investigation and bug fixing reporting (eg https://github.com/csiro-rds/casda_vo_tools/issues/21), I managed to get the service built and running in a docker container. However I was not able to connect to the gleamx db and run queries on it.

**Comment by PaulHancock** [comment]
In branch `23-daiquiri` I tried to use the (Daiquiri)[https://github.com/django-daiquiri/daiquiri] django app which provides an ADQL interface to an existing science database.

The setup of the app was simpler than the previous approach, however I was again not able to properly connect to the gleamx db and run queries on it.

The issue with both of these approaches was incomplete, incorrect, or just confusing documentation.

**Comment by PaulHancock** [comment]
- [ ] Update the filtering of the tables and add a second button which downloads only the data that matches the given query parameters.
