### ISSUE TITLE
Containerise the web app

### ISSUE THREAD

**Issue by PaulHancock** [ADACS-Australia/GleamXGPMonitoring#26]
The web app would be much easier to test and maintain if it were packaged in some docker containers.

Suggest:
- [x] use docker compose
- [x] create dev/prod versions of the setup
- [x] dev version allows live editing and serves via `django runserver`
- [x] prod version embeds all the code and is run via nginx/gunicorn
- [x] include auto heal

**Comment by PaulHancock** [comment]
The web app relies on the [`django-q3c`](https://dev.aao.org.au/datacentral/public/q3c/django-q3c) module, which explicitly asks for `psycopg2`.
However in a containerised solution we want to use `psycopg2-binary`.
For now I have forked the original repo to [my own](https://dev.aao.org.au/paul.hancock/django-q3c.git) and swapped out the dependancy.

**Comment by alexmassen-hane** [comment]
This has been done in the latest PR 'Apply all "Fixed in dev" issues' #38
